### ISSUE TITLE
WARNING: This variable is not defined

### ISSUE THREAD

**Issue by fredycc** [johncmckim/express-to-aws-lambda#4]
When I use: **sls offline start**

I obtain the next output:

> Serverless: Starting Offline: dev/us-east-1.
Serverless: WARNING: This variable is not defined: elastiCacheAddress
Serverless: WARNING: This variable is not defined: elastiCachePort
Serverless: WARNING: This variable is not defined: lambdaExecSecurityGroup
Serverless: WARNING: This variable is not defined: subnetAPrivate

When I run the test, the output is:

> Serverless: POST /users (λ: user-post)
Serverless: The first request might take a few extra seconds
Created memjs client [ '${elastiCacheAddress}:NaN' ]
Creating user { id: 'r16sKRpD',
  username: 'gonto',
  password: 'gonto',
  lastUpdated: Thu Jul 21 2016 00:12:05 GMT-0500 (Central Daylight Time (Mexico)) }
Serverless: Uncaught error in your 'user-post' handler
[ 'RangeError: port should be >= 0 and < 65536: NaN',
  'at lookupAndConnect (net.js:944:13)',
  'at Socket.connect (net.js:921:5)',
  'at Object.exports.connect.exports.createConnection (net.js:69:35)',
  ...]
Serverless: Replying error in handler

After researching, I found that these variables are declared: "_meta / variables"

In my case, "s-variables-common.json", "s-variables-dev-useast1.json", "s-variables-dev.json"

Where could I declare those variables? and what are the values you suggest me?

Thanks for your time.

**Comment by johncmckim** [comment]
@fredycc those variables are created when the project is deployed. They are the CloudFormation outputs of the Elastic Cache, subnets, security groups, ect.

I haven't tried running this offline when using the elastic cache. You could try setting up a local memcached client and add the variables to the `_meta/variables` folder to simulate it offline. However, I have not tried this and am unsure whether that would work.

**Comment by fredycc** [comment]
Thanks @johncmckim for the explanation, you mean to use the command: "serverless dash deploy", right?

**Comment by johncmckim** [comment]
@fredycc `sls dash deploy` should work. I generally use the individual commands: 

```bash
sls resources deploy -r $REGION -s $STAGE
sls function deploy -a -r $REGION -s $STAGE
sls event deploy -a -r $REGION -s $STAGE
sls endpoint deploy -a -r $REGION -s $STAGE
```

Note that this won't run offline. It will run on AWS.
